[build]
  publish = "."
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/api/create-order"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/api/verify-payment"
  to = "/.netlify/functions/verify-payment"
  status = 200

[[edge_functions]]
  function = "inject-env"
  path = "/*"
